version: "3"

services:
  execution-engine:
    image: execution_engine
    environment:
      DB_PATH: "./policy_db/policy.db"
      SELECT_POLICIES_QUERY: "SELECT * FROM policy"
    ports:
      - 5001:5000
    volumes:
      - ./policy_db:/usr/share/script/policy_db
  
  config-frontend:
    image: config_frontend
    ports:
      - 3000:3000

volumes:
  policy_db: